# Generated by Django 4.2.7 on 2026-02-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_login_history_login_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='address',
        ),
        migrations.RemoveField(
            model_name='users',
            name='city',
        ),
        migrations.RemoveField(
            model_name='users',
            name='country',
        ),
        migrations.RemoveField(
            model_name='users',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='users',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='users',
            name='state',
        ),
        migrations.RemoveField(
            model_name='users',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='users',
            name='Experience',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='users',
            name='Full_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='Role',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='users',
            name='targeted_companies',
            field=models.CharField(default='unknown', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Login_history',
        ),
    ]
