# Generated by Django 4.2.7 on 2026-02-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_users_address_remove_users_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Experience',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Full_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Role',
            new_name='role',
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures/'),
        ),
    ]
